Resources:
  EventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.EVENTS_TABLE}
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.USER_TABLE}
Outputs:
  EventsTableName:
    Value:
      Ref: EventsTable
  UserTableName:
    Value:
      Ref: UserTable
