service: ${env:SERVICE_NAME}

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: go1.x
  region: eu-west-2
  logRetentionInDays: 7
  timeout: 10
  versionFunctions: false

package:
  individually: true
  patterns:
    - "!./**"
    - ./bin/**

functions:
  - ${file(src/resources/lambda.yml)}

resources:
  # (HTL - 12/01/24)
  # Users
  # Events
  - ${file(src/resources/dynamo.yml)}
  # (HTL - 12/01/24)
  # Events raw data bucket
  - ${file(src/resources/s3.yml)}
  # (HTL - 12/01/24)
  # Kinesis Firehose
  - ${file(src/resources/kinesis.yml)}
