service: ${env:SERVICE_NAME}

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: go1.x
  region: ${env:AWS_REGION}
  # HTL (12-01-24) Only keep Cloudwatch Logs for 7 days
  logRetentionInDays: 7
  timeout: 10
  versionFunctions: false
  environment:
    EVENTS_TABLE: ${env:EVENTS_TABLE_NAME}
    USERS_TABLE: ${env:USERS_TABLE_NAME}
    ANALYTICS_BUCKET_NAME: ${env:ANALYTICS_BUCKET_NAME}
    KINESIS_STREAM_NAME: ${env:KINESIS_STREAM_NAME}

package:
  individually: true
  patterns:
    - !./**
    - ./bin/**

functions:
  - ${file(resources/lambda.yml)}

resources:
  - ${file(resources/dynamo.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/kinesis.yml)}
